## Task:
** To form a confusion matrix from the given information and derive metrics from it. **

In [103]:
## importing necessary libraries
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [104]:
## defining variables
seed_value = (11,12) #for reproducible results
array_size = 200

seed_value, array_size

((11, 12), 200)

In [105]:
## generating actuals and predictions

np.random.seed(seed_value[0])
actuals = np.random.randint(0,2,array_size)

np.random.seed(seed_value[1])
predictions = np.random.randint(0,2,array_size)

print(actuals[:6])
print(predictions[:6])
print(actuals.size, predictions.size)

[1 1 0 1 1 1]
[1 1 0 1 1 0]
200 200


In [106]:
# forming confusion matrix (actuals/predictions on horizontal/vertical axis respectively)
# Hint : use confusion matric function which we imported earlier
cf = confusion_matrix(actuals,predictions, labels=[0,1])
print(cf)

[[58 40]
 [48 54]]


Expected Outcome <br>
<img src="images/image1.png" />

In [107]:
## Extract True Positive, True Negative, False Positive, False Negative
## Note that all these values are corresponding to class 1

tp = cf[1][1]

fp = cf[1][0]

tn = cf[0][0]

fn = cf[0][1]


print(tp,fp,tn,fn)

54 48 58 40


Expected Outcome<br>
<img src="images/image2.png" />

In [108]:
## Calculate Precision
precision = tp/(tp+fp)

## Calculate Recall
recall = tp/(tp+fn)

## Calculate f1 score
f1 = 2/((1/precision)+(1/recall))

precision, recall, f1

(0.5294117647058824, 0.574468085106383, 0.5510204081632654)

Expected Outcome <br>
<img src="images/image3.png" />